# Generated by Django 5.0.1 on 2024-01-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
